### PR TITLE
ci: use default clippy config with Nix

### PR DESCRIPTION
**Pull request by johnyob**
# Context

Currently we use an oddly specific `clippy` configuration which doesn't encourage best
practices.

# Description

This PR simply uses the default configuration (hooked up with `nix`)

# Manually testing the PR

Green CI 🚀 
or running:
```sh
nix build .#checks.aarch64-darwin.cargo-clippy
```

### CODE REVIEW

**Comment by zcabter** [comment]
Getting this error trying to run the nix flake check command

```
λ nix flake check .#checks.aarch64-darwin.cargo-clippy
error: unexpected fragment 'checks.aarch64-darwin.cargo-clippy' in flake reference '.#checks.aarch64-darwin.cargo-clippy'
```

**Comment by johnyob** [comment]
My bad, I think I meant to write:
```
nix build .#checks.aarch64-darwin.cargo-clippy
```

**Comment by zcabter** [comment]
Got a few warnings but lgtm otherwise. Additionally, the formatting changes look good too! 
```
warning: ignoring untrusted substituter 'https://trilitech-jstz.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
warning: ignoring the client-specified setting 'trusted-public-keys', because it is a restricted setting and you are not a trusted user
warning: could not update mtime for file '/Users/ryan-tan/.cache/nix/gitv3/1l8d5gxl9ayxvlwzmh5wmhhqra2isd70j9zhs8xabfd3sdm7qk1h/refs/heads/ryutamago/fix-undefined-to-json': No such file or directory
```

**Review by zcabter — APPROVED** [review]

**Comment by johnyob** [comment]
> warning: ignoring untrusted substituter 'https://trilitech-jstz.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
warning: ignoring the client-specified setting 'trusted-public-keys', because it is a restricted setting and you are not a trusted user

These warnings related to your local `nix.conf` file, add the following:
```
trusted-users = ryan-tan
```

The other warning persists due to some old Cargo hackery with Boa and patching `mtime`

**Review by zcabter — APPROVED** [review]

**Pull request merged**
